const zone = document.querySelector('.horizontal-zone');
const track = document.querySelector('.horizontal-track');
const slides = document.querySelectorAll('.slide');

function horizontalScroll() {
  if (innerWidth <= 760) {
    track.style.transform = 'none';
    return;
  }
  const start = zone.offsetTop;
  const maxScroll = zone.offsetHeight - innerHeight;
  const progress = Math.max(0, Math.min(1, (scrollY - start) / maxScroll));
  track.style.transform = `translateX(${-progress * (slides.length - 1) * 100}vw)`;
}

addEventListener('scroll', horizontalScroll, { passive: true });
addEventListener('resize', horizontalScroll);
horizontalScroll();

const aboutContent = document.querySelector('.about-content');
aboutContent.innerHTML = `<p class="path">Macintosh HD / Users / Sanghyun</p><p class="intro-status">● CURRENTLY AT ESTGAMES</p><h1>이상현<br><em>인프라·네트워크</em><br>운영 담당자</h1><p class="role-summary"><strong>총 5년 경력</strong>의 IT 인프라 운영 담당자입니다. 사내 네트워크와 업무 시스템을 안정적으로 운영하고, 반복 업무는 자동화와 웹 서비스로 개선합니다.</p><div class="profile-facts"><span><b>FOCUS</b> Network · Firewall · Infrastructure</span><span><b>STACK</b> Docker · Linux · Nginx · FastAPI</span></div>`;
aboutContent.querySelector('h1').innerHTML = `현장과 시스템을 잇는<br><em>네트워크·인프라</em><br>운영 담당자`;
aboutContent.querySelector('.role-summary').innerHTML = `현장의 <strong>네트워크 케이블 포설·단말 연결</strong>부터, 사무실에서의 네트워크 설정·방화벽 관리·IT 인프라 운영까지 담당합니다. 물리와 논리 환경을 함께 이해해 안정적인 업무 흐름을 만듭니다.`;
document.querySelectorAll('.finder-body aside a:not(.selected)').forEach((item) => item.remove());

const terminalBody = document.querySelector('.terminal-body');
terminalBody.innerHTML = `<p class="terminal-prompt"><span>sh@portfolio ~ %</span> hover ./career.log</p><article class="career-hover" tabindex="0"><div class="career-summary"><time>2024 — NOW</time><h2>이스트게임즈 <small>인트라운영팀</small></h2><p>네트워크 운영 · 장애 대응 · 사내 시스템 개발</p></div><ul class="career-detail"><li>사내 네트워크 운영 및 장애 대응, 방화벽 관리</li><li>인트라사이트 및 사내 업무 시스템 개발·유지보수</li><li>사내 IT 인프라 안정화 및 내부 사용자 지원</li><li>PXE 기반 OS 설치·배포 환경 구축</li></ul></article><article class="career-hover" tabindex="0"><div class="career-summary"><time>2020 — 2022</time><h2>타키온테크 <small>기술지원팀</small></h2><p>QA · 모니터링 솔루션 · 현장 기술 지원</p></div><ul class="career-detail"><li>QA 및 자사 툴 모니터링 솔루션 설치·운영</li><li>사용자 현장 교육 및 운영 가이드 지원</li><li>현장 네트워크 라인 포설·단말 연결 및 설치 환경 구성</li><li>공정 데이터 분석</li></ul></article><article class="career-hover" tabindex="0"><div class="career-summary"><time>2019</time><h2>블록체인미르 <small>개발</small></h2><p>웹 퍼블리싱</p></div><ul class="career-detail"><li>웹 페이지 마크업 및 퍼블리싱</li></ul></article><p class="terminal-prompt"><span>sh@portfolio ~ %</span> <b class="cursor">_</b></p>`;

document.querySelectorAll('.career-hover').forEach((entry) => {
  entry.addEventListener('click', () => entry.classList.toggle('is-expanded'));
  entry.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); entry.classList.toggle('is-expanded'); } });
});

const profileAndCareerStyles = document.createElement('style');
profileAndCareerStyles.textContent = `.about-content{padding:27px 50px!important}.intro-status{font-size:10px!important;letter-spacing:.1em;color:#22a96f!important;font-weight:700;margin:0 0 18px!important}.about-content h1{font-size:clamp(37px,4.6vw,60px)!important;margin:0 0 17px!important}.about-content h1 em{color:#426fd7!important}.role-summary{max-width:535px;font-size:16px!important;line-height:1.5!important;color:#505b6c!important;margin:0!important}.role-summary strong{color:#202939}.profile-facts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:22px}.profile-facts span{border:1px solid #d7ddea;border-radius:8px;padding:9px 10px;color:#647087;font-size:10px;line-height:1.35}.profile-facts b{display:block;color:#3d66ba;font-size:9px;letter-spacing:.07em;margin-bottom:2px}.terminal-body{padding:28px 40px!important}.terminal-prompt{margin:0 0 15px!important}.career-hover{padding:14px 0 13px 22px;border-left:1px solid #445064;margin:10px 0;cursor:pointer;outline:none;transition:border-color .2s,background .2s}.career-hover:hover,.career-hover:focus,.career-hover.is-expanded{border-left-color:#67e0b3;background:#ffffff05}.career-summary time{font-size:11px;color:#8792a6}.career-summary h2{font-size:22px;margin:5px 0;color:#f4f7fa}.career-summary h2 small{font-weight:400;font-size:13px;color:#a8b1bf}.career-summary p{margin:0;color:#9facba;font-size:13px}.career-detail{max-height:0;opacity:0;overflow:hidden;margin:0;padding:0 0 0 18px;color:#c3d0dc;font-size:12px;line-height:1.7;transition:max-height .35s ease,opacity .25s ease,margin .35s ease}.career-detail li::marker{color:#68e0b0}.career-hover:hover .career-detail,.career-hover:focus .career-detail,.career-hover.is-expanded .career-detail{max-height:180px;opacity:1;margin:12px 0 0}.terminal .career-hover:last-of-type .career-detail{max-height:0}.terminal .career-hover:last-of-type:hover .career-detail,.terminal .career-hover:last-of-type:focus .career-detail,.terminal .career-hover:last-of-type.is-expanded .career-detail{max-height:60px}@media(max-width:760px){.about-content{padding:28px!important}.profile-facts{grid-template-columns:1fr}.about-content h1{font-size:40px!important}.terminal-body{padding:24px 22px!important}.career-summary h2{font-size:20px}}`;
document.head.append(profileAndCareerStyles);
const profileEmphasisStyles = document.createElement('style');
profileEmphasisStyles.textContent = `.about-content h1{font-size:clamp(34px,4.1vw,54px)!important}.profile-facts{margin-top:27px!important;gap:10px!important}.profile-facts span{min-height:68px;display:flex;flex-direction:column;justify-content:center;background:#ffffff88;box-shadow:0 5px 14px #3242680d;font-size:11px!important}.profile-facts b{font-size:10px!important}.profile-facts .focus-fact{background:linear-gradient(135deg,#e2edff,#d5e6ff);border-color:#8eb6f0;color:#315b99;box-shadow:0 8px 18px #3874bd28;font-size:12px!important}.profile-facts .focus-fact b{color:#2166c2;font-size:11px!important}`;
document.head.append(profileEmphasisStyles);

const menuItems = document.querySelector('.menu-items');
menuItems.innerHTML = `<button data-slide="0">Finder</button><button data-slide="1">프로젝트</button><button data-slide="2">경력</button><button data-slide="3">소개</button>`;
menuItems.querySelectorAll('button').forEach((button) => {
  button.addEventListener('click', () => {
    const targetIndex = Number(button.dataset.slide);
    if (innerWidth <= 760) {
      slides[targetIndex].scrollIntoView({ behavior: 'smooth', block: 'start' });
      return;
    }
    const targetProgress = targetIndex / (slides.length - 1);
    const targetTop = zone.offsetTop + (zone.offsetHeight - innerHeight) * targetProgress;
    scrollTo({ top: targetTop, behavior: 'smooth' });
  });
});
const menuStyles = document.createElement('style');
menuStyles.textContent = `.menu-items{display:flex;gap:12px}.menu-items button{border:0;background:transparent;padding:0;color:#555;font:inherit;font-size:11px;cursor:pointer}.menu-items button:hover,.menu-items button:focus-visible{color:#0a84ff;outline:none}`;
document.head.append(menuStyles);

const projectGuide = document.createElement('p');
projectGuide.className = 'project-click-guide';
projectGuide.textContent = '폴더를 클릭해 구조 보기';
document.querySelector('.folder-grid').append(projectGuide);
const projectGuideStyles = document.createElement('style');
projectGuideStyles.textContent = `.folder-grid{position:relative}.project-click-guide{position:absolute;z-index:6;left:50%;top:50%;transform:translate(-50%,-50%);margin:0;padding:9px 14px;border:1px solid #d5dbe7;border-radius:99px;background:#ffffffde;box-shadow:0 8px 20px #29375214;color:#57657d;font-size:12px;letter-spacing:-.02em;pointer-events:none;white-space:nowrap}.project-click-guide span{font-size:16px;color:#4389df;vertical-align:-1px;margin-right:3px}@media(max-width:760px){.project-click-guide{font-size:10px;padding:7px 10px}.project-click-guide span{font-size:13px}}`;
document.head.append(projectGuideStyles);
projectGuideStyles.textContent += `.folder:after{display:none!important}`;
projectGuideStyles.textContent += `.project-click-guide{animation:guidePulse 1.8s ease-in-out infinite}@keyframes guidePulse{0%,100%{transform:translate(-50%,-50%) scale(1);box-shadow:0 8px 20px #29375214}50%{transform:translate(-50%,-50%) scale(1.045);box-shadow:0 10px 27px #4389df42}}@media(prefers-reduced-motion:reduce){.project-click-guide{animation:none}}`;

const projectDialog = document.createElement('div');
projectDialog.className = 'project-dialog';
projectDialog.setAttribute('role', 'dialog');
projectDialog.setAttribute('aria-modal', 'true');
projectDialog.setAttribute('aria-hidden', 'true');
document.body.append(projectDialog);

function closeProjectWindow() {
  projectDialog.classList.remove('is-open');
  projectDialog.setAttribute('aria-hidden', 'true');
}

const flowDiagrams = {
  mint: `<div class="flow-diagram"><p class="flow-caption">Docker 기반 통합 관리 시스템</p><div class="flow-row"><div class="flow-node client">▣<b>Browser UI</b><small>JavaScript</small></div><i>→</i><div class="flow-node proxy">↔<b>Nginx</b><small>Reverse Proxy</small></div><i>→</i><div class="flow-node api">◈<b>FastAPI</b><small>API Service</small></div></div><div class="flow-down">↓</div><div class="flow-row data-row"><div class="flow-node database">▤<b>MySQL</b><small>재고 · 포트 정보</small></div><i>→</i><div class="flow-node result">⌘<b>좌석 구성도</b><small>장비 · 포트 시각화</small></div></div><p class="flow-foot">Nginx · FastAPI · PHP · MySQL 컨테이너 분리 운영</p></div>`,
  blue: `<div class="flow-diagram"><p class="flow-caption">서버 모니터링 데이터 흐름</p><div class="flow-row"><div class="flow-node client">▣<b>Linux Server</b><small>CPU · Memory · Disk</small></div><i>→</i><div class="flow-node proxy">◉<b>Checkmk Agent</b><small>자원 수집</small></div><i>→</i><div class="flow-node result">▥<b>Checkmk</b><small>Dashboard</small></div></div><div class="flow-down">↓</div><div class="flow-row data-row"><div class="flow-node database">!<b>이상 징후</b><small>상태 감지</small></div><i>→</i><div class="flow-node result">⌘<b>운영 대응</b><small>사전 확인</small></div></div><p class="flow-foot">실시간 상태 확인으로 장애 대응 속도 개선</p></div>`,
  purple: `<div class="flow-diagram"><p class="flow-caption">PXE 기반 OS 설치 흐름</p><div class="flow-row"><div class="flow-node client">▣<b>Client PC</b><small>Network Boot</small></div><i>→</i><div class="flow-node proxy">◈<b>iVentoy</b><small>PXE Server</small></div><i>→</i><div class="flow-node api">▤<b>OS Image</b><small>Install Source</small></div></div><div class="flow-down">↓</div><div class="flow-row data-row"><div class="flow-node database">↻<b>자동 설치</b><small>반복 작업 표준화</small></div><i>→</i><div class="flow-node result">✓<b>Ready PC</b><small>설치 완료</small></div></div><p class="flow-foot">iVentoy 기반 네트워크 부팅 자동화 환경</p></div>`,
  orange: `<div class="flow-diagram"><p class="flow-caption">VLAN 네트워크 구성 흐름</p><div class="flow-row"><div class="flow-node client">●<b>사용자 단말</b><small>부서별 PC</small></div><i>→</i><div class="flow-node proxy">▦<b>Managed Switch</b><small>VLAN 설정</small></div><i>→</i><div class="flow-node api">⌁<b>네트워크</b><small>부서별 분리</small></div></div><div class="flow-down">↓</div><div class="flow-row data-row"><div class="flow-node database">⌘<b>관리 구조</b><small>가시성 향상</small></div><i>→</i><div class="flow-node result">✓<b>안정적 연결</b><small>업무 중단 최소화</small></div></div><p class="flow-foot">스위치 교체와 VLAN 구성으로 보안·관리 효율 향상</p></div>`
};

// 프로젝트마다 실제 시스템의 복잡도가 달라, 노드 수와 창 밀도를 의도적으로 다르게 둡니다.
Object.assign(flowDiagrams, {
  mint: `<div class="flow-diagram diagram-infra"><p class="flow-caption">Docker 기반 통합 관리 시스템</p><div class="flow-row"><div class="flow-node client">▣<b>Browser UI</b><small>JavaScript</small></div><i>→</i><div class="flow-node proxy">↔<b>Nginx</b><small>Reverse Proxy</small></div><i>→</i><div class="flow-node api">◈<b>FastAPI</b><small>API Service</small></div></div><div class="infra-link"><div><b>FastAPI</b><span>API 요청 처리</span></div><strong>⇄</strong><div><b>MySQL</b><span>재고 · 포트 데이터</span></div><small>데이터 조회 · 수정</small></div><div class="infra-output"><span>FastAPI API Response</span><i>→</i><div class="flow-node result">⌘<b>좌석 구성도</b><small>장비 · 포트 시각화</small></div></div><p class="flow-foot">Nginx · FastAPI · PHP · MySQL 컨테이너 분리 운영</p></div>`,
  blue: `<div class="flow-diagram diagram-medium"><p class="flow-caption">서버 모니터링 데이터 흐름</p><div class="flow-row"><div class="flow-node client">▣<b>Linux Server</b><small>CPU · Memory · Disk</small></div><i>→</i><div class="flow-node proxy">◉<b>Checkmk Agent</b><small>자원 수집</small></div><i>→</i><div class="flow-node result">▥<b>Checkmk Dashboard</b><small>상태 확인</small></div></div><div class="flow-down">↓</div><div class="flow-row compact-row"><div class="flow-node database">!<b>이상 징후 감지</b><small>운영자가 선제 대응</small></div></div><p class="flow-foot">수집 → 관찰 → 대응의 4단계 운영 흐름</p></div>`,
  purple: `<div class="flow-diagram diagram-medium"><p class="flow-caption">PXE 기반 OS 자동 설치 흐름</p><div class="flow-row"><div class="flow-node client">▣<b>Client PC</b><small>Network Boot</small></div><i>→</i><div class="flow-node proxy">◈<b>iVentoy</b><small>PXE 환경</small></div></div><div class="flow-down">↓</div><div class="flow-row"><div class="flow-node api">▤<b>OS Image</b><small>Install Source</small></div><i>→</i><div class="flow-node result">✓<b>설치 완료 PC</b><small>표준화된 배포</small></div></div><p class="flow-foot">네트워크 부팅 이후 설치 이미지를 배포하는 4단계 흐름</p></div>`,
  orange: `<div class="flow-diagram diagram-short"><p class="flow-caption">VLAN 네트워크 구성 흐름</p><div class="flow-row"><div class="flow-node client">●<b>사용자·부서</b><small>각 단말</small></div><i>→</i><div class="flow-node proxy">▦<b>Managed Switch</b><small>VLAN 설정</small></div><i>→</i><div class="flow-node result">⌁<b>분리된 네트워크</b><small>안정적 연결</small></div></div><p class="flow-foot">스위치의 VLAN 설정으로 부서별 망을 분리하는 3단계 구조</p></div>`
});

// 어떤 화살표도 두 개의 노드 사이를 가리키지 않도록, 각 프로젝트를 명시적인 단방향 흐름으로 표현합니다.
Object.assign(flowDiagrams, {
  blue: `<div class="flow-diagram diagram-medium"><p class="flow-caption">서버 모니터링 데이터 흐름</p><div class="flow-row"><div class="flow-node client">▣<b>Linux Server</b><small>CPU · Memory · Disk</small></div><i>→</i><div class="flow-node proxy">◉<b>Checkmk Agent</b><small>자원 수집</small></div><i>→</i><div class="flow-node api">▥<b>Checkmk</b><small>상태 분석</small></div><i>→</i><div class="flow-node result">!<b>운영 Dashboard</b><small>이상 징후 대응</small></div></div><p class="flow-foot">서버 지표가 수집되어 운영 화면에서 확인되는 단방향 흐름</p></div>`,
  purple: `<div class="flow-diagram diagram-wide"><p class="flow-caption">PXE 기반 OS 자동 설치 흐름</p><div class="flow-row"><div class="flow-node client">▣<b>Client PC</b><small>Network Boot</small></div><i>→</i><div class="flow-node proxy">◈<b>iVentoy</b><small>PXE 환경</small></div><i>→</i><div class="flow-node api">▤<b>OS Image</b><small>Install Source</small></div><i>→</i><div class="flow-node result">✓<b>설치 완료 PC</b><small>표준화된 배포</small></div></div><p class="flow-foot">네트워크 부팅부터 설치 완료까지 한 번에 이어지는 4단계 흐름</p></div>`
});

Object.assign(flowDiagrams, {
  mint: `<div class="flow-diagram diagram-infra2"><p class="flow-caption">Docker 기반 통합 관리 시스템</p><div class="infra-top"><div class="flow-node client">▣<b>Browser UI</b><small>JavaScript</small></div><i>→</i><div class="flow-node proxy">↔<b>Nginx</b><small>Reverse Proxy</small></div><i>→</i><div class="flow-node api">◈<b>FastAPI</b><small>API Service</small></div></div><div class="infra-db-lane"><div class="lane-arrow"><span>데이터 조회 · 수정</span><i>↕</i></div><div class="flow-node database">▤<b>MySQL</b><small>재고 · 포트 정보</small></div></div><div class="infra-response"><span>FastAPI API Response</span><i>→</i><div class="flow-node result">⌘<b>좌석 구성도</b><small>장비 · 포트 시각화</small></div></div><p class="flow-foot">Nginx · FastAPI · PHP · MySQL 컨테이너 분리 운영</p></div>`
});

flowDiagrams.mint = `<div class="flow-diagram diagram-network"><p class="flow-caption">Docker 기반 통합 관리 시스템</p><div class="system-map"><svg viewBox="0 0 860 360" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="flow-arrow" markerWidth="9" markerHeight="9" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#4c9ce6"/></marker></defs><path d="M170 100 L250 100" marker-end="url(#flow-arrow)"/><path d="M410 100 L490 100" marker-end="url(#flow-arrow)"/><path d="M570 155 L570 230" marker-start="url(#flow-arrow)" marker-end="url(#flow-arrow)"/><path d="M650 112 C735 112 705 220 700 220" marker-end="url(#flow-arrow)"/></svg><div class="system-node browser">▣<b>Browser UI</b><small>JavaScript</small></div><div class="system-node nginx">↔<b>Nginx</b><small>Reverse Proxy</small></div><div class="system-node fastapi">◈<b>FastAPI</b><small>API Service</small></div><div class="system-node mysql">▤<b>MySQL</b><small>재고 · 포트 정보</small></div><div class="system-node seat">⌘<b>좌석 구성도</b><small>장비 · 포트 시각화</small></div><span class="db-label">데이터 조회 · 수정</span><span class="response-label">API Response</span></div><p class="flow-foot">Nginx · FastAPI · PHP · MySQL 컨테이너 분리 운영</p></div>`;

flowDiagrams.mint = `<div class="flow-diagram diagram-network"><p class="flow-caption">Docker 기반 통합 관리 시스템</p><div class="system-map"><svg viewBox="0 0 860 360" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="flow-arrow" markerWidth="9" markerHeight="9" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#4c9ce6"/></marker></defs><path d="M170 100 L250 100" marker-end="url(#flow-arrow)"/><path d="M410 100 L490 100" marker-end="url(#flow-arrow)"/><path d="M650 100 L700 100" marker-end="url(#flow-arrow)"/><path d="M570 155 L570 230" marker-start="url(#flow-arrow)" marker-end="url(#flow-arrow)"/></svg><div class="system-node browser">▣<b>Browser UI</b><small>JavaScript</small></div><div class="system-node nginx">↔<b>Nginx</b><small>Reverse Proxy</small></div><div class="system-node fastapi">◈<b>FastAPI</b><small>API Service</small></div><div class="system-node mysql">▤<b>MySQL</b><small>재고 · 포트 정보</small></div><div class="system-node seat">⌘<b>좌석 구성도</b><small>장비 · 포트 시각화</small></div><span class="db-label">데이터 조회 · 수정</span><span class="response-label">API Response</span></div><p class="flow-foot">Nginx · FastAPI · PHP · MySQL 컨테이너 분리 운영</p></div>`;
flowDiagrams.mint = flowDiagrams.mint.replace(' marker-start="url(#flow-arrow)" marker-end="url(#flow-arrow)"', ' marker-end="url(#flow-arrow)"').replace('데이터 조회 · 수정', 'DB 데이터 조회 · 수정');
flowDiagrams.mint = `<div class="flow-diagram diagram-network"><p class="flow-caption">Docker 기반 통합 관리 시스템</p><div class="system-map"><div class="system-node browser">▣<b>Browser UI</b><small>JavaScript</small></div><span class="map-arrow arrow-one">→</span><div class="system-node nginx">↔<b>Nginx</b><small>Reverse Proxy</small></div><span class="map-arrow arrow-two">→</span><div class="system-node fastapi">◈<b>FastAPI</b><small>API Service</small></div><span class="map-arrow arrow-three">→</span><div class="system-node seat">⌘<b>좌석 구성도</b><small>장비 · 포트 시각화</small></div><span class="map-arrow arrow-down">↓</span><div class="system-node mysql">▤<b>MySQL</b><small>재고 · 포트 정보</small></div><span class="db-label">DB 데이터 조회 · 수정</span><span class="response-label">API Response</span></div><p class="flow-foot">Nginx · FastAPI · PHP · MySQL 컨테이너 분리 운영</p></div>`;

flowDiagrams.mint = `<div class="flow-diagram diagram-roundtrip"><p class="flow-caption">Docker 기반 통합 관리 시스템</p><div class="flow-lane request-lane"><span class="lane-label">01 REQUEST</span><div class="lane-chain"><div class="round-node browser-node">▣<b>Browser UI</b><small>요청</small></div><i>→</i><div class="round-node nginx-node">↔<b>Nginx</b><small>Reverse Proxy</small></div><i>→</i><div class="round-node api-node">◈<b>FastAPI</b><small>API 처리</small></div><i>→</i><div class="round-node db-node">▤<b>MySQL</b><small>재고 · 포트 조회</small></div></div></div><div class="flow-lane response-lane"><span class="lane-label">02 RESPONSE</span><div class="lane-chain"><div class="round-node db-node">▤<b>MySQL Result</b><small>조회 결과</small></div><i>→</i><div class="round-node api-node">◈<b>FastAPI</b><small>응답 데이터 생성</small></div><i>→</i><div class="round-node nginx-node">↔<b>Nginx</b><small>응답 전달</small></div><i>→</i><div class="round-node browser-node">▣<b>Browser UI</b><small>화면 렌더링</small></div><i>→</i><div class="round-node result-node">⌘<b>좌석 구성도</b><small>장비 · 포트 시각화</small></div></div></div><p class="flow-foot">Nginx · FastAPI · PHP · MySQL 컨테이너 분리 운영</p></div>`;

function openProjectWindow(folder) {
  const name = folder.querySelector(':scope > b').textContent;
  const preview = Object.keys(flowDiagrams).map((key) => folder.classList.contains(key) ? flowDiagrams[key] : null).find(Boolean) || folder.querySelector('.folder-preview').innerHTML;
  projectDialog.innerHTML = `<div class="project-window-modal window"><div class="titlebar"><button class="close-window" aria-label="창 닫기"></button><i></i><i></i><strong>${name}</strong></div><div class="modal-content"><p class="modal-path">Projects / ${name}</p>${preview}</div></div>`;
  projectDialog.classList.add('is-open');
  projectDialog.setAttribute('aria-hidden', 'false');
  projectDialog.querySelector('.close-window').addEventListener('click', closeProjectWindow);
}

document.querySelectorAll('.folder').forEach((folder) => {
  folder.addEventListener('click', () => openProjectWindow(folder));
  folder.addEventListener('keydown', (event) => {
    if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openProjectWindow(folder); }
  });
});
addEventListener('keydown', (event) => { if (event.key === 'Escape') closeProjectWindow(); });
projectDialog.addEventListener('click', (event) => { if (event.target === projectDialog) closeProjectWindow(); });

const interactionStyles = document.createElement('style');
interactionStyles.textContent = `.folder:hover{transform:none}.folder:hover .folder-preview,.folder:focus .folder-preview{display:none}.folder{cursor:pointer}.folder:after{content:'클릭해서 열기';display:block;margin-top:7px;font-size:10px;color:#657084;opacity:0;transition:opacity .2s}.folder:hover:after,.folder:focus:after{opacity:1}.project-dialog{position:fixed;z-index:50;inset:0;display:none;place-items:center;background:#0a153866;backdrop-filter:blur(10px);padding:22px}.project-dialog.is-open{display:grid}.project-window-modal{width:min(690px,92vw);min-height:430px;background:#f7f8fc;box-shadow:0 35px 100px #07152c80;animation:open-window .28s cubic-bezier(.2,.9,.3,1)}.close-window{width:12px;height:12px;border:0;border-radius:50%;background:#ff5f57;padding:0;cursor:pointer}.close-window:hover{filter:brightness(.78)}.project-window-modal .titlebar i{background:#febc2e}.project-window-modal .titlebar i:nth-of-type(2){background:#28c840}.modal-content{padding:35px 42px}.modal-path{font-size:11px;color:#758093;margin:0 0 24px}.modal-content .folder-preview{display:block;position:static;transform:none;width:100%;min-height:0;padding:0;background:transparent;box-shadow:none;color:#202534}.modal-content .folder-preview h2{font-size:32px;letter-spacing:-.055em;margin-bottom:25px}.modal-content .folder-preview p{font-size:15px;padding:15px;border-color:#d7dce6;background:#fff}.modal-content .folder-preview i{color:#2272d8}.modal-content .folder-preview span{display:block;margin-top:22px;color:#687386;font-size:12px}@keyframes open-window{from{opacity:0;transform:scale(.92) translateY(18px)}to{opacity:1;transform:none}}@media(max-width:760px){.project-dialog{padding:12px}.modal-content{padding:28px 22px}.modal-content .folder-preview h2{font-size:26px}}`;
document.head.append(interactionStyles);

const diagramStyles = document.createElement('style');
diagramStyles.textContent = `.modal-content .flow-diagram{display:block;color:#263147}.flow-caption{font-size:14px!important;font-weight:700;color:#66758f!important;margin:0 0 24px!important}.flow-row{display:flex;align-items:stretch;justify-content:center;gap:10px}.flow-node{min-width:0;flex:1;min-height:100px;border:1px solid #c7d0df;border-radius:12px;background:linear-gradient(135deg,#fff,#edf3fb);display:grid;place-content:center;text-align:center;color:#2877cf;font-size:19px;box-shadow:0 5px 14px #315c9012}.flow-node b,.flow-node small{display:block}.flow-node b{font-size:13px;color:#263147;margin-top:5px}.flow-node small{font-size:10px;color:#738198;margin-top:3px}.flow-node.proxy{background:linear-gradient(135deg,#e0f5ff,#c9e6ff);color:#1581c4}.flow-node.api{background:linear-gradient(135deg,#dbeaff,#c6d6ff);color:#5c5fd4}.flow-node.database{background:linear-gradient(135deg,#e4fff4,#c6efdc);color:#139474}.flow-node.result{background:linear-gradient(135deg,#fff4dd,#ffe4b1);color:#dd7a1f}.flow-row>i{align-self:center;color:#4c9ce6;font-style:normal;font-size:23px;font-weight:300}.flow-down{text-align:center;color:#4c9ce6;font-size:24px;line-height:1;margin:10px}.data-row{max-width:73%;margin:auto}.flow-foot{font-size:11px!important;color:#7b8799!important;text-align:center;margin:23px 0 0!important;padding-top:15px;border-top:1px dashed #cbd4e1}@media(max-width:600px){.flow-row{gap:4px}.flow-node{min-height:88px;font-size:16px}.flow-node b{font-size:10px}.flow-node small{font-size:8px}.flow-row>i{font-size:16px}.data-row{max-width:100%}.modal-content .flow-diagram{overflow-x:auto}.flow-foot{font-size:10px!important}}`;
document.head.append(diagramStyles);
const projectGridStyles = document.createElement('style');
projectGridStyles.textContent = `.project-window{height:760px}.folder-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:68px 115px;padding:58px 105px}.folder{height:270px}.folder-icon{height:195px;font-size:44px}.folder-icon:before{width:92px;height:32px;top:-21px}.folder b{font-size:19px;margin-top:21px}.folder>small{font-size:11px}@media(max-width:760px){.project-window{height:auto}.folder-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:40px 18px;padding:55px 24px}.folder{height:195px}.folder-icon{height:110px;font-size:30px}.folder-icon:before{width:62px;height:24px;top:-16px}.folder b{font-size:14px;margin-top:18px}.folder>small{font-size:9px}}`;
document.head.append(projectGridStyles);
projectGridStyles.textContent += `.project-window-modal:has(.diagram-wide){width:min(800px,94vw);min-height:360px}.diagram-wide .flow-node{min-height:110px}`;

document.querySelector('.dock')?.remove();
const contactContent = document.querySelector('.contact-content');
contactContent.innerHTML = `<div class="profile-photo-wrap"><img src="./profile-photo.png" alt="이상현 프로필 사진"></div><div class="profile-copy"><p class="contact-kicker">LET'S WORK TOGETHER</p><h2>새로운 문제를<br>함께 풀어볼까요?</h2><p class="profile-name">이상현 <span>Infrastructure & Network Operations</span></p><a href="mailto:aromad1117@naver.com">aromad1117@naver.com</a><a href="tel:01066850145">010 6685 0145</a></div>`;
const finalContactStyles = document.createElement('style');
finalContactStyles.textContent = `.closing-slide{background:linear-gradient(135deg,#bddcff,#a7b9fa 49%,#c8a8ed)}.contact-card{width:min(820px,90vw);background:#f8f9fdde}.contact-content{padding:38px 48px;display:grid;grid-template-columns:285px 1fr;gap:44px;text-align:left;align-items:center}.profile-photo-wrap{height:330px;border-radius:18px;overflow:hidden;background:#dce3f3;box-shadow:0 14px 30px #37467c30}.profile-photo-wrap img{width:100%;height:100%;object-fit:cover;object-position:center}.contact-kicker{font-size:11px!important;letter-spacing:.12em!important;color:#6577bd!important;margin:0 0 16px!important}.profile-copy h2{font-size:clamp(37px,4vw,55px)!important;line-height:.96!important;letter-spacing:-.07em!important;margin:0 0 24px!important}.profile-name{font-size:16px!important;color:#20283a!important;margin:0 0 20px!important}.profile-name span{font-size:11px;color:#73809a;margin-left:8px}.profile-copy a{display:block;font-size:17px;color:#386bd5;margin:8px 0;text-decoration:none}.profile-copy a:hover{text-decoration:underline}.end-note{color:#fff}@media(max-width:650px){.contact-content{grid-template-columns:1fr;padding:28px;gap:28px}.profile-photo-wrap{height:250px;max-width:300px}.profile-copy h2{font-size:39px!important}.profile-copy a{font-size:16px}}`;
document.head.append(finalContactStyles);

document.querySelector('.folder-toolbar small').textContent = '폴더를 클릭해 구조 보기';
const projectLayoutFixStyles = document.createElement('style');
projectLayoutFixStyles.textContent = `.project-window{height:min(720px,calc(100svh - 80px))}.folder-grid{padding:42px 105px;gap:42px 115px}.folder{height:235px}.folder-icon{height:165px}.folder-icon:before{top:-19px}.folder b{margin-top:18px}.infra-top{display:grid;grid-template-columns:1fr 28px 1fr 28px 1fr;gap:8px;align-items:center}.infra-top>i{font-size:23px;color:#4c9ce6;text-align:center;font-style:normal}.infra-db-lane{width:30%;margin:13px 0 13px auto;text-align:center}.lane-arrow{display:grid;justify-items:center;color:#4c9ce6;margin:4px 0 7px}.lane-arrow span{font-size:10px;color:#687b96;background:#f7f8fc;padding:0 5px}.lane-arrow i{font-style:normal;font-size:23px;line-height:1}.infra-db-lane .flow-node{min-height:78px}.infra-response{display:flex;align-items:center;justify-content:flex-end;gap:10px;margin-top:15px}.infra-response>span{font-size:11px;color:#71809a}.infra-response>i{font-style:normal;color:#4c9ce6;font-size:20px}.infra-response .flow-node{flex:0 0 170px;min-height:72px}@media(max-width:760px){.project-window{height:auto}.folder-grid{padding:55px 24px;gap:40px 18px}.folder{height:195px}.folder-icon{height:110px}.infra-top{grid-template-columns:1fr 15px 1fr 15px 1fr;gap:3px}.infra-top>i{font-size:16px}.infra-db-lane{width:42%;margin-left:auto}.infra-response>span{font-size:9px}.infra-response .flow-node{flex-basis:135px}.lane-arrow span{font-size:8px}}`;
document.head.append(projectLayoutFixStyles);
const networkDiagramStyles = document.createElement('style');
networkDiagramStyles.textContent = `.project-window-modal:has(.diagram-network){width:min(980px,95vw);min-height:550px}.diagram-network{overflow:visible!important}.system-map{width:860px;height:360px;max-width:100%;margin:0 auto;position:relative}.system-map svg{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.system-map svg path{stroke:#4c9ce6;stroke-width:2;fill:none}.system-node{position:absolute;width:160px;height:110px;border:1px solid #c7d0df;border-radius:12px;background:linear-gradient(135deg,#fff,#edf3fb);display:grid;place-content:center;text-align:center;color:#2877cf;font-size:20px;box-shadow:0 5px 14px #315c9012}.system-node b,.system-node small{display:block}.system-node b{font-size:13px;color:#263147;margin-top:5px}.system-node small{font-size:10px;color:#738198;margin-top:3px}.system-node.browser{left:10px;top:45px}.system-node.nginx{left:250px;top:45px;background:linear-gradient(135deg,#e0f5ff,#c9e6ff);color:#1581c4}.system-node.fastapi{left:490px;top:45px;background:linear-gradient(135deg,#dbeaff,#c6d6ff);color:#5c5fd4}.system-node.mysql{left:490px;top:230px;background:linear-gradient(135deg,#e4fff4,#c6efdc);color:#139474}.system-node.seat{left:700px;top:165px;background:linear-gradient(135deg,#fff4dd,#ffe4b1);color:#dd7a1f}.db-label,.response-label{position:absolute;padding:3px 7px;border-radius:99px;background:#f7f8fc;color:#657893;font-size:10px}.db-label{left:583px;top:180px}.response-label{left:674px;top:123px}.diagram-network .flow-foot{margin-top:6px!important}@media(max-width:700px){.project-window-modal:has(.diagram-network){width:95vw}.modal-content:has(.diagram-network){padding:26px 16px;overflow-x:auto}.system-map{min-width:860px}.diagram-network .flow-caption{padding-left:8px}}`;
document.head.append(networkDiagramStyles);
const roundtripStyles = document.createElement('style');
roundtripStyles.textContent = `.project-window-modal:has(.diagram-roundtrip){width:min(1080px,96vw);min-height:500px}.diagram-roundtrip{overflow:visible!important}.flow-lane{padding:15px 0 18px;position:relative}.flow-lane+.flow-lane{border-top:1px dashed #ccd5e2}.lane-label{display:inline-block;margin:0 0 11px;padding:4px 8px;border-radius:99px;background:#eaf2ff;color:#4683cd;font-size:10px;font-weight:700;letter-spacing:.08em}.response-lane .lane-label{background:#eefaf4;color:#278761}.lane-chain{display:flex;align-items:center;gap:8px}.round-node{flex:1;min-width:0;min-height:90px;border:1px solid #c7d0df;border-radius:11px;background:linear-gradient(135deg,#fff,#edf3fb);display:grid;place-content:center;text-align:center;color:#2877cf;font-size:17px;box-shadow:0 5px 14px #315c9012}.round-node b,.round-node small{display:block}.round-node b{font-size:12px;color:#263147;margin-top:4px}.round-node small{font-size:9px;color:#738198;margin-top:3px}.lane-chain>i{font-style:normal;font-size:22px;font-weight:300;color:#4c9ce6}.nginx-node{background:linear-gradient(135deg,#e0f5ff,#c9e6ff);color:#1581c4}.api-node{background:linear-gradient(135deg,#dbeaff,#c6d6ff);color:#5c5fd4}.db-node{background:linear-gradient(135deg,#e4fff4,#c6efdc);color:#139474}.result-node{background:linear-gradient(135deg,#fff4dd,#ffe4b1);color:#dd7a1f}.diagram-roundtrip .flow-foot{margin-top:16px!important}@media(max-width:720px){.project-window-modal:has(.diagram-roundtrip){width:95vw}.modal-content:has(.diagram-roundtrip){padding:26px 16px;overflow-x:auto}.diagram-roundtrip{min-width:890px}.round-node{min-height:82px}.lane-chain>i{font-size:18px}}`;
document.head.append(roundtripStyles);
networkDiagramStyles.textContent += `.system-map svg{display:none}.map-arrow{position:absolute;z-index:2;color:#4c9ce6;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Malgun Gothic",sans-serif;font-size:26px;font-weight:300;line-height:1}.arrow-one{left:205px;top:86px}.arrow-two{left:445px;top:86px}.arrow-three{left:665px;top:86px}.arrow-down{left:558px;top:162px}.db-label{left:581px;top:181px}.response-label{left:654px;top:21px}`;
networkDiagramStyles.textContent += `.system-node.seat{top:45px}.response-label{left:650px;top:21px;white-space:nowrap}.db-label{left:583px;top:180px}`;
diagramStyles.textContent += `.project-window-modal:has(.diagram-medium){min-height:385px;width:min(630px,92vw)}.project-window-modal:has(.diagram-short){min-height:330px;width:min(590px,92vw)}.compact-row{max-width:42%;margin:auto}.diagram-short .flow-row{max-width:88%;margin:20px auto}.diagram-short .flow-foot{margin-top:28px!important}.infra-link{position:relative;display:flex;justify-content:center;align-items:center;gap:18px;margin:18px auto 15px;width:min(360px,90%);padding:12px;border:1px dashed #aabbd2;border-radius:10px;background:#f8fbff;text-align:center}.infra-link div b,.infra-link div span{display:block}.infra-link div b{font-size:12px}.infra-link div span{font-size:10px;color:#728096;margin-top:3px}.infra-link strong{font-size:22px;color:#3688d9}.infra-link small{position:absolute;top:-9px;left:50%;transform:translateX(-50%);padding:0 6px;background:#f8fbff;color:#69788e;font-size:10px;white-space:nowrap}.infra-output{display:flex;align-items:center;justify-content:center;gap:10px;margin-top:14px}.infra-output>span{font-size:11px;color:#71809a}.infra-output>i{font-style:normal;font-size:20px;color:#4c9ce6}.infra-output .flow-node{flex:0 0 170px;min-height:70px}@media(max-width:600px){.compact-row{max-width:70%}.project-window-modal:has(.diagram-medium),.project-window-modal:has(.diagram-short){width:92vw}.infra-link{gap:10px}.infra-output .flow-node{flex-basis:135px}.infra-output>span{font-size:9px}}`;
